### ISSUE TITLE
Pagination for video galleries

### ISSUE THREAD

**Issue by muleymadness** [kylegilman/video-embed-thumbnail-generator#187]
Is it possible to add pagination for my thumbnail video galleries?  Say I only want to display 9 videos per page, can I then have a page 2 etc. for all remaining videos?  If so how, I can't figure it out.

**Comment by muleymadness** [comment]
Looks like you added this functionality in the most recent build here, is there a way to set the number of videos that displays per page before page 2 appears etc? Looks to me that currently it's defaulting to 2 videos per page. I assume this isn't quite ready yet and you'll add that ability in the future.

**Comment by kylegilman** [comment]
Anything hosted here is not ready for prime time. You can see that my commit on Dec 1 says I'm working on it. And the issue is still open. It's set to 2 videos per page so it's easier to test. There are a bunch of things that don't work right yet. Please be patient.

**Comment by muleymadness** [comment]
Thanks for the update, I'll try to be more patient.

**Comment by kylegilman** [comment]
Need to test pagination with all sort order options. Make sure we never display all attachments by accident.
