### ISSUE TITLE
Thumbnails generate but do not upload and apply.

### ISSUE THREAD

**Issue by LaserLag** [kylegilman/video-embed-thumbnail-generator#205]
I am using Chrome (Version 41.0.2272.101 m). I'm trying to generate a thumbnail on an already uploaded .mp4 video. The video is to be embedded on a post with the default Wordpress player and using your embed shortcode. 

Here are the steps I am taking:
1. Start creation of a new post.
2. Click "Add Media" button.
3. Click on the existing .mp4 video in the media library tab.
4. The "Attachment Details" show on the right of the media library.
5. Under "Thumbnails" I click "Choose from video..."
6. A little player pops down with a slider underneath to choose the frame.
7. I find the frame I like and click the "Use this frame" button.
8. It seems to generate the thumbnail - an image of the frame I selected pops up right below.
9. Now the issue. The "Thumbnail URL" field does not populate. The selected frame does not show up in the media library.
10. I press "Insert into post". The video embeds properly but there is no thumbnail for it and no featured image.

Some other details:
* The .mp4 video is 720p 60FPS but I have tested it with a 30FPS video with the same results. I have tried several other 720p 60FPS and 30FPS .mp4 videos with no luck.
* It worked like 1 time randomly.
* I've tried disabling all other plugins.
* I've tried uninstalling and reinstalling the plugin.
* I tried 1 smaller resolution video (352x240) and it is successfully setting the thumbnail every time.

Please let me know if you need any other information from me!

**Comment by kylegilman** [comment]
Do you have the same problem in other browsers? What OS are you using? Can you open the JavaScript Console in Chrome and let me know if you see any error messages?

**Comment by LaserLag** [comment]
I have tried Firefox and experienced the same issue. Using Windows 8.1. I will try checking the JavaScript Console now.

**Comment by LaserLag** [comment]
Upon choosing a frame and pressing "Use this frame":

    POST http://theduds.org/wp-admin/admin-ajax.php 413 (Request Entity Too Large)load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=4.1.1:4 m.ajaxTransport.sendload-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload,json2&ver=4.1.1:4 m.extend.ajaxkgvid_video_plugin_admin.js?ver=4.42:405 kgvid_save_canvas_thumbkgvid_video_plugin_admin.js?ver=4.42:493 kgvid_thumb_video_manualpost.php?post=597&action=edit&message=1:1 onclick

**Comment by kylegilman** [comment]
Your server is configured to only allow very small file transfers through PHP. That's why you were able to make the thumbnail for the lowres video but not 720p ones. The fix depends on the server you're running and how much access you have to configuration files. This should help you get started: http://craftcms.stackexchange.com/questions/2328/413-request-entity-too-large-error-with-uploading-a-file

**Comment by LaserLag** [comment]
Thank you!

**Comment by LaserLag** [comment]
Any other advice? I have been troubleshooting some more. My max upload size in PHP is set to 128MB. Following that link you posted, in .htaccess I set LimitRequestBody to something much higher with no success. I'm not sure what else to try.

**Comment by kylegilman** [comment]
I've never seen someone have this problem before, so I don't know any more about it than you do. If you can look at your server's error logs, you might get a more specific error message. This link has some more things to try. http://serverfault.com/questions/402630/http-error-413-request-entity-too-large

**Comment by LaserLag** [comment]
Thanks for the reply. This link also has good info: http://www.mokonamodoki.com/windows-phone-8-wordpress-app-media-upload-error

Specifically: 
> By default, the SecRequestBodyNoFilesLimit value in my ModSec configuration file was 131072 (bytes). That is to say, according to ModSecurity, a post submission (a submission of data posted to the web server, not to be confused with a WordPress post entry) can contain no more than 128KB of data. Pretty much any picture or photo will likely be larger than 128KB.

This makes sense as the few thumbnails that did work correctly were topping out around ~120KB and never over. Now I just need to see if I can get that setting changed. I did try setting it in my .htaccess file but it crashed out my site. I'll try to contact my host. Thanks again!

**Comment by kylegilman** [comment]
Closing old issues. If you still need support, leave a comment and I'll re-open it.

**Comment by kylegilman** [comment]
Since it's been happening more frequently lately, I need to do some error handling for this issue.
