### ISSUE TITLE
Thumbnail creation

### ISSUE THREAD

**Issue by muleymadness** [kylegilman/video-embed-thumbnail-generator#217]
Does the plugin create a variety of thumbnail sizes or just one?  It appears on my server there is 5 different thumbnail sizes being created...just curious if my theme is doing this or your plugin.

And is it possible to change or adapt how many are being generated, I'm hoping to upload LOTS of 20-30 second clips and don't want my server full of unnecessary clutter, images, to fill up space.

I have the general settings to 1 thumbnail, but it's generating 5 every time.

**Comment by kylegilman** [comment]
The plugin registers one full-size image with the WordPress Media Library. Whatever happens after that is up to your theme or WordPress media settings.
