### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by luc7v** [kylegilman/video-embed-thumbnail-generator#218]
Hi,
I need to add subtitles to some video.

With the Video.js, it works, but:
1. Is it a way to make the text for subtitles bigger? I can hardly read it.
2. Is it a way to activate subtitles by default?

I wanted to try the Wordpress player, but:
3. On the settings page, the player preview doesn't show up.
4. The pages with video on them doesn't load at all.

So I switched back to Video.js and it's OK again.

All the best,
Lucian

**Comment by kylegilman** [comment]
In the current release, the active by default option is not enabled. It wasn't possible in older versions of video.js but it is now. If you want to live on the edge you can try the development version I'm working on by downloading it from GitHub. There's a chance that some elements won't work, and you might get some bugs, but it's fairly stable right now. https://github.com/kylegilman/video-embed-thumbnail-generator/archive/master.zip

You can style the video.js subtitles using the `.video-js .vjs-subtitles` CSS class.

I don't know why the WordPress default player isn't working on your site. I might be able to help if you post a link so I can troubleshoot it.

**Comment by kylegilman** [comment]
Version 4.5 is released and includes an option to turn on subtitles by default. I'm closing this issue for now, but if you still need support, post a comment and I'll open it again.

**Comment by luc7v** [comment]
I updated the plugin and now the subtitles doesn't work at all.

You can check at
http://miratico.ro/olga-murray-de-la-copilaria-in-transilvania-la-copiii-din-nepal/

**Comment by kylegilman** [comment]
I didn't know about this, but apparently srt files used to sort of work with Video.js before v4.12 was released and then they stopped working. It should be simple for you to convert srt files to WebVTT format. There are some links to utitlites in this Video.js support forum https://github.com/videojs/video.js/issues/1956

If you have too many srt tracks to convert, I'm looking in to adding srt support. There's a plugin for Video.js called BubblesJS that adds support for srt. I'm going to look into it and see if it makes sense to include in my plugin.

**Comment by luc7v** [comment]
I see.

Another cool idea is that your plugin to convert SRT to WebVTT

**Comment by luc7v** [comment]
I converted SRT to WebVTT and I can see the subtitles now.

But the subtitles are not enabled by default, despite the fact that I checked Default box.

**Comment by kylegilman** [comment]
It works in Chrome on my computer, but not in any other browser. Again it looks like Video.js hasn't quite fixed this yet. https://github.com/videojs/video.js/issues/1914

I do think I can make this one work though.

**Comment by luc7v** [comment]
Yes, it seems to work only on Chrome

**Comment by kylegilman** [comment]
Closing old issues. As far as I can tell the default option works in all browsers now.
