### ISSUE TITLE
video-embed-thumbnail-generator on mobile device

### ISSUE THREAD

**Issue by Clem625** [kylegilman/video-embed-thumbnail-generator#219]
Hi, 
I have created a website with Maximus template. 
I use your video plugin, it works very well but when i visit my website with a tablet or a smartphone, i'm not able to view the videos. I get a black screen or a screenshot image of the video without any button "Play" and it's not responsive.
What is the solution to solve this problem?
(Sorry my english)

**Comment by kylegilman** [comment]
Please post a link to your site so I can troubleshoot it.

**Comment by Clem625** [comment]
Hi,
 Here is a link to an exemple :

 http://www.image-et-process.com/blog/2015/05/27/test-video/.

The player is responsive only on Firefox. On safari (windows and ipad), the video doesn't play.

**Comment by kylegilman** [comment]
I'm seeing a lot of 502 Bad Gateway errors in the JavaScript console which is preventing a number of JavaScripts from loading, most importantly jQuery, which is used by several scripts in both your theme and my plugin. I can't troubleshoot the problem myself. It's a

**Comment by Clem625** [comment]
OK
Thanks for your help and your time

**Comment by kylegilman** [comment]
Closing old issues. If you still have a problem, add a comment and I'll open it up again.
