### ISSUE TITLE
I don't see the FFMPEG tab mentioned in previous support answers.  

### ISSUE THREAD

**Issue by hefejeff** [kylegilman/video-embed-thumbnail-generator#224]
I am trying to get thumbnails created each time I upload a video to our sites media library.  I had our server admin install FFMPEG but I do not see any tab for FFMPEG where I can set this up.

**Comment by kylegilman** [comment]
On the Video Embed & Thumbnail Generator settings page there should be a tab at the top of the page called "FFMPEG Settings" 

It's not on your settings page?

![ffmpeg settings](https://cloud.githubusercontent.com/assets/4528113/8192050/8d7077f6-1439-11e5-83f5-4148c8f8e2f3.jpg)

**Comment by hefejeff** [comment]
Nope.
![screen shot 2015-06-16 at 1 17 54 pm](https://cloud.githubusercontent.com/assets/9152006/8192290/53c35ae6-142a-11e5-8a58-32049e4ab5e0.png)

**Comment by hefejeff** [comment]
Ok... I see something.  I am using multisites.  I went to the network settings page and do see settings.  I will check with my server admin and make sure that the path is correct.  Should I see this tab on the individual sites setup pages though?

**Comment by kylegilman** [comment]
Oh, on a multisite network you have to set up the path to FFMPEG in the network settings page first. Otherwise the tab is hidden because it's useless on a network without FFMPEG.

**Comment by hefejeff** [comment]
All working now.  Thanks for the help

**Comment by kylegilman** [comment]
Great! Good luck with your project.

**Comment by hefejeff** [comment]
Thanks for the help.  One question.  Do you ever do any side work.  Our
project requires a lot of video recording, editing, rendering and uploading
between a phone app and a wordpress multisite system.  If you have the time
we will surely need some assistance in the near future and are willing to
pay for your help.

Jeff Wells
Quepos, Costa Rica

On Wed, Jun 17, 2015 at 9:52 AM, Kyle Gilman <notifications@github.com>
wrote:

> Great! Good luck with your project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kylegilman/video-embed-thumbnail-generator/issues/224#issuecomment-112858077>
> .
>



-- 
Jeff Wells
+506-8845-5993
