### ISSUE TITLE
add hotspot jwplayer

### ISSUE THREAD

**Issue by JeyEm1986** [kylegilman/video-embed-thumbnail-generator#233]
In addition to setting-caption subtitles and chapter also add the ability to insert hotspots as jwplayer "http://www.jwplayer.com/innovation/experiments/hot-spots/"

**Comment by kylegilman** [comment]
That's a custom JavaScript experiment that JW Player offers as an example of things you can do with their API and is not actually a feature of their player or any of the players included with this plugin. Implementing this would be fairly difficult. I wouldn't count on this becoming a feature any time soon.

**Comment by JeyEm1986** [comment]
ok, I thank you for the quick response will remain waiting for this development officer meanwhile do you propose another perhaps more feasible
