### ISSUE TITLE
add download file from video [jwplayer]

### ISSUE THREAD

**Issue by JeyEm1986** [kylegilman/video-embed-thumbnail-generator#234]
Now you can add the download of the video with a click from the media library. If you add the download of a file from video by specifying the file link or a file taken from the media library.
I mean the download button by jw player in the top left of cms wordpress.

**Comment by kylegilman** [comment]
I'm sorry, I thought I understood what you were asking, but when I started working on it I realized I didn't. Can you explain it a little more?

**Comment by kylegilman** [comment]
Closing old issues. If you still want support for this add a comment and I'll re-open.

**Comment by JeyEm1986** [comment]
Hi Kile,
what I meant with my bad English was to provide for the possibility to add a button in the overlay to the player to download a file taken from direct url or from library. With jwplayer it is possible to add a like button "share."

**Comment by kylegilman** [comment]
That sounds like the download icon I made in the latest release. Does that not do what you want it to?

**Comment by kylegilman** [comment]
Or do you want to be able to download a different file that is not the video file?
