### ISSUE TITLE
Generating thumbnails for videos with arabic names/titles ?

### ISSUE THREAD

**Issue by Hazemwd** [kylegilman/video-embed-thumbnail-generator#246]
When I upload a video file with arabic name, the thumbnail is generated but is neither loaded into the post as featured image nor viewed in the wordpress media upload box, but it is uploaded successfully and named like this

Ø¨Ø§Ù„ÙÙŠØ¯ÙŠÙˆ..-ÙÙŠÙ†Ø¬Ø±-ÙŠØ´ØªØ¨Ùƒ-Ø¨Ù…ÙˆØ±ÙŠÙ†ÙŠÙˆ-Ø£Ø«Ù†Ø§Ø¡-Ø§Ù„Ù…Ø¨Ø§Ø±Ø§Ø©-Ù…ØµØ±-Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©_thumb3

How to solve this ?
Thanks.

@kylegilman

**Comment by kylegilman** [comment]
Are you using FFMPEG or in-browser thumbnail creation?

**Comment by Hazemwd** [comment]
I configured it to automatically generate a thumbnail, I also tried to generate it from the plugin options in the media upload box but both don't work.

**Comment by Hazemwd** [comment]
In addition to that the "in browser .." option is enabled.

**Comment by kylegilman** [comment]
I ran some tests with Arabic characters in video filenames on my own server and didn't have any trouble making thumbnails. I've never had any other Arabic users experience this problem. I think there has to be another issue at work here. Something to do with your server configuration perhaps. It seems like an unusual character encoding issue, but I don't know enough about the problem to offer much help getting to the bottom of it if I can't replicate the issue myself.

**Comment by Hazemwd** [comment]
The thumbnails are generated successfully as  I mentioned but with weird names like
Ø¨Ø§Ù„Ù�ÙŠØ¯ÙŠÙˆ..-Ù�ÙŠÙ†Ø¬Ø±-ÙŠØ´ØªØ¨Ùƒ-Ø¨Ù…ÙˆØ±ÙŠÙ†ÙŠÙˆ-Ø£Ø«Ù†Ø§Ø¡-Ø§Ù„Ù…Ø¨Ø§Ø±Ø§Ø©-Ù…ØµØ±-Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©_thumb3

they are neither loaded into the media library box nor set as a featured image.
The problem as I think is that they are named with these weird characters and then they are called with their original Arabic names. So the problem is in the naming of the files when they are written to the filesystem.

**Comment by kylegilman** [comment]
This appears to be a problem with Windows. It is Windows-1256 encoding. This hasn't come up before because Linux and Mac servers do not have this problem when working with videos that have Arabic names. The thumbnails are generated, saved in the Media Library and set as featured images, always maintaining the Arabic characters. Are you planning to use a Windows server for your final site, or is this just for testing?

**Comment by Hazemwd** [comment]
The deployment server is Linux (CentOS), but I'm using the windows machine for testing and development.

**Comment by kylegilman** [comment]
Closing old issues. If you still want support for this, add a comment and I'll re-open.
