### ISSUE TITLE
How to add a dropdown menu to the media uploader containing a list of my custom taxonomies.

### ISSUE THREAD

**Issue by Hazemwd** [kylegilman/video-embed-thumbnail-generator#248]
Hello @kylegilman 

Suppose I have a select element containing a list of my custom taxonomies or terms, I need to add it to the media library uploader so that the admin can choose the custom taxonomy to which he wants to add this bulk of files once these files are uploaded successfully, and each file has its own post.
I asked you before about the ability to generate a post for each uploaded file and you "thanked" told me to use the "add_attachment" HOOK.
I'm trying here to pass the taxonomy and the term IDs to the wp_set_object_terms() function after using wp_insert_post function.

Another thought is to attach a meta data for each uploaded video/attachment, this meta data is the term of the attachment, then I'll develop a function which the user will call to generate a post for each attachment containing that meta data.

How to achieve this (adding the dropdown menu to the media library box) ?
THANKS.

**Comment by kylegilman** [comment]
This is not a question about my plugin. Please look elsewhere for that kind of help.
