### ISSUE TITLE
How to tell the plugin to encode videos located in specific folder on the server and add them to the media library

### ISSUE THREAD

**Issue by Hazemwd** [kylegilman/video-embed-thumbnail-generator#249]
I'm trying to let the admin encode episodes located in a folder on the server and add them to the media library.
What I'm asking about here is how to tell the plugin to encode the videos located in that directory for example:-
    
    grabs/series/dexter/

as if I uploaded them from the wordpress media uploader.
THANKS in advance.

**Comment by kylegilman** [comment]
Nope. Television pirates get no help here.

**Comment by Hazemwd** [comment]
I'm saying ((((for example)))),
my website is for anime series.
