### ISSUE TITLE
Embed videos from katch.me

### ISSUE THREAD

**Issue by latinoise** [kylegilman/video-embed-thumbnail-generator#255]
Would like ability to enable Periscope replays saved at katch.me to be able to embed with this plugin.

sample katch.me embed code...

<iframe width="640" height="569" src="https://katch.me/embed/v/b6e60797-1152-3608-84cf-a7faf55a2b5d?sync=1" frameborder="0" scrolling="no" allowfullscreen></iframe>

**Comment by kylegilman** [comment]
You don't need my plugin to embed katch.me videos. Just use the iframe embed code they provide.

**Comment by latinoise** [comment]
Im sorry I meant to generate thumbnails from katch.me iframe code.

**Comment by kylegilman** [comment]
This plugin doesn't make thumbnails for videos hosted on services like YouTube, Vimeo, etc. katch.me is one of thousands of these services. I'm not comfortable with the legal implications of making copies of framegrabs and I don't want to play catch-up every time they change their API.
