### ISSUE TITLE
HTTP error & black post thumbnails generated

### ISSUE THREAD

**Issue by pattnnet** [kylegilman/video-embed-thumbnail-generator#264]
Hey Kyle,
i'm using your plugin and having some issues. I'm on bluehost  @PHP 5.4.43 @64BitOS Version 4.3.1
max_file_size is set to 250MB.

When i try to upload videos, i get an HTTP Error often. After having a look at the error logs i found this error:

14-Aug-2015 06:11:07 UTC] PHP Fatal error:  Call to undefined method WP_Error::get_size() in /home1/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 5082

Some older already uploaded files worked great, but i cant change the thumbnail afterwards, if i want to select a frame from video - and click on use this frame - often the image turns black. Any idea how to solve this?

Thanks a lot! 
pattn

**Comment by kylegilman** [comment]
I just moved to a new apartment and we're having a baby any day now so my support will not be very speedy for a little while. I'll look into this as soon as I have a spare minute.

**Comment by pattnnet** [comment]
No problem Kyle, 

congratulations on becoming a dad! 













          Patrick Romer 
 <http://www.pattn.net/>          info@pattn.net <mailto:info@pattn.net>
          PATTN - kommunikationsdesign 
          +49 40 357 759 56 
          www.pattn.net <http://www.pattn.net/>

**Comment by kylegilman** [comment]
Sorry this took forever to get back to. I think the thumbnail saving and uploading issues are two different problems. That PHP error is confusing because there's no get_size() call on line 5082 in version 4.5.5. What version of the plugin are you using? 

Also, do the HTTP errors go away when you disable the plugin? Do you have FFMPEG setup on your server?

**Comment by kylegilman** [comment]
Closing old issues. If you still want support for this problem, post a comment and I'll re-open.
