### ISSUE TITLE
Videojs: This is not function

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#268]
Hi,

sometimes after page load when a video is embedded I get: 
Uncaught TypeError: this[a] is not a function(anonymous function) @ video.js?ver=4.12.11:60t.i.ca @ video.js?ver=4.12.11:13t.Player.t.a.extend.l @ video.js?ver=4.12.11:59d @ video.js?ver=4.12.11:6t @ video.js?ver=4.12.11:3t.uc @ video.js?ver=4.12.11:185
videojs-media-sources.js?ver=2.4.1:144 Uncaught TypeError: videojs.extend is not a function(anonymous function) @ videojs-media-sources.js?ver=2.4.1:144(anonymous function) @ videojs-media-sources.js?ver=2.4.1:1113

Can you tell me a little bit more about that?

Regards,

**Comment by kylegilman** [comment]
I've never seen that before and it's hard to tell what's causing the error without seeing a live page. Can you post a link to a page that generates this error?

**Comment by benhartwich** [comment]
I think, it´s related to other videojs files, which comes from theme files. I´ve commented the enqueue lines out, because the video-js queue is called similar to your script call, so I can´t properly dequeue it. Perhaps you can considering renaming your script queue?
