### ISSUE TITLE
Extension: VOD Streaming (Wowza Media Server)

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#277]
Hi,

we use the wowza media server to stream videos. A colleague has extended your plugin to this functionality: If it´s activated all videos are stored at one location under wp-content - on this way all videos can be synced via rsync to the vod folder at the wowza media server after all videos are encoded through your plugin. All embed codes except the embedding code for the video itself at the player are rewrited to the wowza streaming integration. Also dash.js etc. is activated: the three encoded qualities are streamed dynamically with the wowza transcoder engine.

You can have a look at: https://develop.intelec.uni-passau.de/gitlab/medien/vod-streaming

We would appreciate, if you can integrate this functionality to your plugin.

Regards,

**Comment by kylegilman** [comment]
I'm happy to add the necessary filter to the plugin, but not enthusiastic about adding specific support for a  commercial streaming service. Once the filter is added you can continue to use your extension and shouldn't have to edit the core plugin file every time you upgrade.

**Comment by kylegilman** [comment]
I added a modified filter. I changed the filter name to `kgvid_single_video_code`, and it's not necessary to pass the $options array, so I eliminated it. The filter function can get the $options array using a command like this:

`if ( function_exists('kgvid_get_options') ) { $options = kgvid_get_options(); }`

**Comment by n0risc** [comment]
Hello @benhartwich . Thanks for your code implementing this. With this also work with .m3u8 manifests?

**Comment by benhartwich** [comment]
Hi @n0risc please it supports all modern browser, also mobile. Just try it out, but only normal vod applications from wowza. 
@kylegilman Thank you! please give me a hint, if you have implemented it.

**Comment by benhartwich** [comment]
It works, thanks @kylegilman

**Comment by kylegilman** [comment]
Be advised, I just revised this filter in 7231a6b3c798c6e119ba021f899f3639829da7fb
