### ISSUE TITLE
Vod Streaming: Rewriting embed links

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#280]
Hi,

I´ve published the link to our VOD Streaming Plugin for a while - based on your plugin. What would be the best way to rewrite the video embed code at the videojs player to the new media links, which are generated by VOD streaming? 

Example video: https://iliastest.intelec.uni-passau.de/wordpress/2015/12/zmk-film/

Regards,

**Comment by kylegilman** [comment]
You can use the shortcode attribute `embedcode` to change the video embed code to any HTML code you want.
