### ISSUE TITLE
Translation: blank .po with source strings

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#283]
Hi,

can you please send me the "raw" .po file for translating your plugin into german?

Thanks!

**Comment by benhartwich** [comment]
Got it.

**Comment by kylegilman** [comment]
If you're translating into German, there's already someone else working on the current release. Take a look at the project on the new [WordPress translation hub](https://translate.wordpress.org/locale/de/default/wp-plugins/video-embed-thumbnail-generator). I would really appreciate it if you could complete the translation. They don't get released until they reach 100%. I can make you a moderator so you don't have to get approval for your translations.

**Comment by benhartwich** [comment]
OK, you can add me: yoursql719 is my username.
