### ISSUE TITLE
Possibility not automatically encode specific videos

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#284]
Hi,

I´ve activated the option per default, that uploaded videos are encoded automatically. Is there any workaround / possibility to define a way where uploaded videos are not automatically encoded, when this option is active?

I´ve the following problem: There are videos, which have not the best chroma subsampling by device and are rendered by Adobe Premiere / Media Encoder for best encoding quality. Such videos should not be encoded again via ffmpeg. But there also will be videos, which should be encoded automatically by the default procedure.

Can you give me a hint how this problem can be adressed? Perhaps you can add this to your feature list?

Regards,

**Comment by kylegilman** [comment]
Off the top of my head, if you created a file naming structure that tells the plugin what to do that could work. For example, anything with the text 'noreplace' wouldn't get replaced. Or just let FFMPEG re-encode all your videos. That's what YouTube and Vimeo and every other video hosting site does.

**Comment by benhartwich** [comment]
OK, is this behaviour already a feature, where I can set xy-noreplace.mp4 and the original is not replaced, but all lower qualities are encoded? If not, I would like to do feature request :)

**Comment by kylegilman** [comment]
This is not already a feature. I'm not sure this will be useful to anyone else, but I'll consider adding it in the future.

**Comment by benhartwich** [comment]
Would be great - I see this feature specially for video producer, who would like to publish their video content for high quality purposes, which is made by Adobe Premiere or other tools. To find a common compromise to address both scenarios would be less possible only with ffmpeg, would it be?

**Comment by kylegilman** [comment]
I added this feature while I was working on #244 which had similar functions.

**Comment by benhartwich** [comment]
Thank you very much. It works!
