### ISSUE TITLE
Automatically set featured image of video thumbnails works sometimes

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#285]
Hi,

I´ve set "Set generated video thumbnails as featured images" and attach all thumbnails to post. But sometimes the automatically generated thumbnails are not set as featured image and I don´t know why. 

I´ve tested with option  "When possible, use the browser's built-in video capabilities to make thumbnails instead of FFMPEG." but I found no rule oder behaviour to reproduce it certainly. This problem occurs for a long time. Most of the time there is no problem, but sometimes it doesn´t work.
How can I investigate it further?

Regards,

**Comment by kylegilman** [comment]
When you have this problem are the thumbnails created and attached to the post or attached to the video? Whenever I've seen this issue in the past it's because the video wasn't actually attached to the post at the time the thumbnails were made. Have you verified that the post is the video's parent in the WordPress database? You can see which videos are uploaded to which post in list view in the Media Library (wp-admin/upload.php?mode=list). The column "Uploaded to" needs to be the post you're expecting to have the featured image set to. Also, are you using any sort of front-end uploader?

**Comment by benhartwich** [comment]
Thumbnails and videos are always attached to the post. Yes, videos are uploaded by a frontend uploader, which attaches the video file to the post (at media at backend all is attached fine), which is created by the form. After this form is sent, the post is published, while ffmpeg renders the video file when the upload is finished - in most cases before the post is published.

Do you think, it happens, when the post (form) is published too fast or too slow, while ffmpeg is rendering at the background?

Can you tell me a workaround to create a cronjob for the setting: Set all as featured at the plugin settings?

**Comment by kylegilman** [comment]
There seem to be times when frontend uploaders create the database entry for the video before they create the post, and only set the post parent after the thumbnails are created, so the plugin has to watch for changes in the video's parent and re-set the post parents of all the thumbnails when that happens. The plugin was not setting the featured image when this happens. I added a function to set the featured image whenever the post parent changes if there's not already a featured image for the post. This should fix your problem.

**Comment by benhartwich** [comment]
Hi,
unfortunately the bug isn´t fixed. I´ve installed the fix, but now there are set no thumbnails any more.

**Comment by kylegilman** [comment]
Probably because I created another bug while I was creating the new function. I think it will work now. It's hard to tell because I can't actually test it out without buying one of these frontend uploaders.

**Comment by benhartwich** [comment]
I can send you the frontend uploader for testing. The new version seems to work, but I´ve to test more videos till I know, if it´s really working.

**Comment by kylegilman** [comment]
If it's a plugin you paid for, I'm sure that's against the terms of the license agreement.

**Comment by benhartwich** [comment]
I think, I can still send you the plugin. there is no activation code or similar which has to be provided. Let me know, how I can send you the plugin. Still it does not work correctly.

**Comment by kylegilman** [comment]
Just because there's no activation code it doesn't mean that you can send it to me. I'm not interested in ripping off hardworking WordPress developers if they've chosen to charge for their work. What is the name of the plugin? Maybe I can test with a free version of it.

**Comment by benhartwich** [comment]
Yes there´s a free version, but I don´t know, if you can test it really. But you can try: https://de.wordpress.org/plugins/accesspress-anonymous-post/

**Comment by kylegilman** [comment]
I tried the free version but it sets the video's parent to the post that the submission form is associated with, which isn't helpful. Unless you can do the troubleshooting yourself I really can't spend any more time on this issue that only affects one user.

**Comment by benhartwich** [comment]
No problem, but can you provide me information, about how to set all thumbnails as featured image, where no featured image is available for a cron job? I think this would be great little help tool.

**Comment by kylegilman** [comment]
Closing old support issues. If you're still experiencing a problem please open a new issue.
