### ISSUE TITLE
kgvid_styles.css is breaking iPhone 5s, 6 and 6+ playbutton in JWPlayer 6.12.4956 Latest

### ISSUE THREAD

**Issue by n0risc** [kylegilman/video-embed-thumbnail-generator#302]
JWPlayer had just release a new version of the 6.12 player updated through their CDN.. We had noticed clients complaining the Play Button would not work on iPhone 5s, 6, 6+ devices. I have found the issue. When removing kgvid.styles.css from the scope, the player renders fine.  I'm not sure if it's just a clash of CSS from JWPlayer Plugin and KGVID. That I do not know. Just reporting it. I will report back on which specific CSS entry is causing the Play Button not to render.

**Comment by kylegilman** [comment]
I haven't been able to duplicate this on my test site. Can you give me a link to a post that demonstrates the problem?

**Comment by kylegilman** [comment]
Unfortunately the JW Player 6 WordPress plugin doesn't work very well anymore. I'm seeing a lot of errors in WordPress 4.5 testing. They've removed it from the WordPress plugin database and their JW Player 7 plugin works in a totally different way. I'm not going to remove the JW Player 6 option from my plugin, but I can't dedicate a lot of time to keeping it working now that they've abandoned it.

**Comment by n0risc** [comment]
It was an error on my part. You can close this.
