### ISSUE TITLE
Video controlls and resolution selector missing on mobile

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#317]
![screenshot_mobile](https://cloud.githubusercontent.com/assets/4061954/14421325/4431c7e6-ffd1-11e5-93f1-76ea34804d16.png)
After pausing or muting a playing video the controls are gone away and a click into the playing video doesn´t show up any controls. I´ve tested this bevahiour in two browser at my android phone. 

Also I can´t select any resolution any more. Can you reproduce this bug?

**Comment by kylegilman** [comment]
I can't reproduce that bug on Android 5.0. Make sure you clear your caches so the most recent JS files are loaded. What version of Android is this?

**Comment by benhartwich** [comment]
I use Android 5.1.1 on a Oneplus 2. I´ve reverted to an older version and deactivated a few plugins, but the problem persists. How can I investigate it further?

**Comment by kylegilman** [comment]
I need a link to a live page demonstrating the problem.

**Comment by benhartwich** [comment]
For example: http://univideo.uni-passau.de/2016/04/lehrvideo-fussball-frontaler-kopfstoss/

**Comment by kylegilman** [comment]
This video loads the video-js player with the resolution selector button on three different Android phones I tested just now. Please test it on a different device that has never loaded your site in the past. If you're still having a problem, try remote debugging. https://developer.chrome.com/devtools/docs/remote-debugging and see if you get any error messages. 

The default HTML5 video player is always loaded by every browser on every device. Video-js is just a skin on the default player. The time at which you see the transition from the default to the video-js skin will vary on different devices. If there is a JavaScript error on the page, that can cause the problem you're seeing.

**Comment by benhartwich** [comment]
Hi, I´ve updated the plugin from github on a test site, where you can view the problem: 
http://univideo-test.uni-passau.de/2016/03/collapsed-minds-neuroleptic-empire-official-music-video-2015/

I´ve visited the site never before, because it´s a fresh clone, so I think there is no caching problem.

**Comment by benhartwich** [comment]
At Google Chrome Inspect I got the warning: 
video.js?ver=5.5.3:1 Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user

**Comment by kylegilman** [comment]
That message is just letting you know that the mobile browser, like most mobile browsers, doesn't allow autoplay. The "Native controls on mobile devices" plugin setting is enabled on this test site. Try turning it off.

**Comment by benhartwich** [comment]
OK, I think this setting was causing problems.
