### ISSUE TITLE
Feature: Custom video start point

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#323]
Hi,

I´ve got a feature request - I´ve nothing at the official documation, so I think it´s not possible for now: A custom video starts at cue-in marker would be great - similar to YouTube video time marks.

Video JS Player would support this.

Regards,

**Comment by kylegilman** [comment]
That is not a feature of the plugin at the moment. I might get around to it some day, but I'm not adding any new features until I finish and release version 4.6, which has been delayed for too long.
