### ISSUE TITLE
Autoplay Parameter on Embedding videos

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#325]
Hi,

when I enable autoplay for general, embedded video are played automatically too, which I can´t control.
Is there any URL parameter to stop this or can you please integrate a rule for this scenario?

Regards,

**Comment by kylegilman** [comment]
So you want your videos to always autoplay on your site but you don't want them to autoplay when they're embedded using the iframe code? Since you have a do_shortcode template code generating your videos, why not add the autoplay="true" attribute to that code and disable the global plugin option?

**Comment by benhartwich** [comment]
Thanks, worked!
