### ISSUE TITLE
PHP Shortcode changed?

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#326]
Hi,

on Update to 4.6.1 I can´t play any video because the shortcode doesn´t run at header.php.
if ($file != NULL && !has_shortcode( $content, '[KGVID]') ) {

                            echo do_shortcode('[KGVID autoplay="true"]'.$file.'[/KGVID]');

                            } else {
....
Has the shortcode changed?

**Comment by kylegilman** [comment]
No of course the shortcode didn't change overnight. Do you see a video that doesn't work or do you see the text of the shortcode in your post? Are you getting any errors in your error log? Is the plugin deactivated somehow?

**Comment by benhartwich** [comment]
Oh I´m stupid, plugin was deactivated by update. Sorry.
