### ISSUE TITLE
on backdated video post when encoded new post should use date of original video post

### ISSUE THREAD

**Issue by n0risc** [kylegilman/video-embed-thumbnail-generator#329]

**Comment by kylegilman** [comment]
Just like on #324, I need details when you post issues. Please don't just put in a long title and expect me to know what you're talking about. Walk me through this process. What is a video post? What is a backdated video post? When a video is encoded, how is a new post created and what date does it have and how is that affecting your site?

**Comment by n0risc** [comment]
Sorry Kyle.

I'm using the plugin "Add From Server" which allows to make a video post of the file time, and sticks it in the appropriate /uploads/sites/x/year/month/.    When KGVID makes video posts of the original video post, it uses the current date/time and not the date/time of the original post. thus video files are in two locations.

**Comment by kylegilman** [comment]
You've updated to version 4.6 and this is still happening?

**Comment by n0risc** [comment]
I have not... I've made some small modifications to 4.6, and can't upgrade to 4.6.1 yet. But I will do this later today, and report back.

Zach.

**Comment by kylegilman** [comment]
Starting with version 4.6 the plugin is supposed to encode videos in the same folder as the original as long as that folder is writeable.

**Comment by n0risc** [comment]
I may have a branch of 4.6 before that was done. I had not upgraded to 4.6 from Wordpress. I grabbed it from GitHub. That could be the culprit.

**Comment by kylegilman** [comment]
I made that change in 607c23f318b2ce7f9f05a3ee14a0b1fa304d0532 on March 4
