### ISSUE TITLE
JW Player 6 latest 2.1.15 not loading in 6.1 or 6.2

### ISSUE THREAD

**Issue by n0risc** [kylegilman/video-embed-thumbnail-generator#331]
Hi Kyle:

All other players appear in the settings page, except JW Player on new release 6.2.

**Comment by n0risc** [comment]
Kyle:

I have reverted to 6.0, and JW Player 6 version 2.1.15 latest release from github, is now loading again.  Not sure why it is not in 6.1 or 6.2.   Latest Wordpress 4.5.1

**Comment by kylegilman** [comment]
I assume you mean version 4.6 of my plugin? I can't duplicate this bug. JW Player appears in the list of available players in 4.6.2 and there's nothing that's changed from 4.6 to 4.6.2 that affects JW Player. When you update to 4.6.2, verify that the JW Player plugin is active. That's the only reason I know of that the JW Player option wouldn't be available.

**Comment by n0risc** [comment]
Okay.. Strange that the player is not showing up in the settings page when 4.6.1 or 4.6.2 is installed.  I will dig deeper.

**Comment by kylegilman** [comment]
I think I found the problem. Remember that whatever you're using that calls itself version 4.6 was not the final version released to the public as version 4.6. In 96f9c9c20f988e4cc56381e2a960fb26b742aecd on March 8, I changed the _value_ of the JW Player option when I meant to change the label. I'll fix this in the next release.

**Comment by n0risc** [comment]
Thanks Kyle... Yes, 4.6.4 fixed it.
