### ISSUE TITLE
Adding chapters

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#332]
Hi,

is the chapter functionality fully integrated? 

I´ve tested it at an example and created a .vtt file with subtitle edit online. The text is displayed but I think there should be any list with the different chapters at the video js player when I hit the button next to the quality switcher, shouldn´t it?
You can see an example here: https://univideo.uni-passau.de/2013/11/einfuehrung-videotechnik-2/

Can you please tell me, what are the default steps to integrate chapters? 
I´ve also recognized that saving a file at "add track" with track type "chapter" the field track type switches back to subtitles when the media is saved.

Regards,

**Comment by kylegilman** [comment]
Looks like the chapter menu is broken in the version of Video.js I'm using. Unfortunately the resolution switcher is broken in the versions that fix the chapter menu. These things are related I'm sure. For now I'm sacrificing the chapter menu function until I can get the resolution switching to work with later versions of Video.js

I fixed the bug that made the menu selection always say subtitles.

**Comment by kylegilman** [comment]
This should be fixed now in 1ba3704f5d37389ad4b6144849d464b686aae5b9
