### ISSUE TITLE
Chapters: Display the subtitle anytime?

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#339]
Hi,

I´ve tried the chapters feature of the video js player: a chapter, which is currently playing, is visible as subtitle everytime. Have you experience, if there is possibility to show up a new chapter only for a few seconds as subtitle?

Regards,

**Comment by kylegilman** [comment]
Just a guess since I've never used chapters, but have you tried changing the length of the chapter to only a few seconds? I would assume that you only need a start time to make a chapter work and the end time would determine how long the subtitle appears.

**Comment by benhartwich** [comment]
Thanks for the patch!
