### ISSUE TITLE
.mov encoding produces 404 errors

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#346]
Hi,

when a -mov video is encoded it produces an 404 error for the original file, which is replaced by mp4 encoded file: 
https://univideo.uni-passau.de/wp-content/uploads/2016/05/trauer-ein-gesellschaftliches-konstrukt.mov?id=0 Failed to load resource: the server responded with a status of 404 ()

How can I solve this problem. At mp4 videos the problem doesn´t occur only at other file types, whenever they are re-encoded to mp4.

Regards,

**Comment by kylegilman** [comment]
I can't duplicate this myself. Did this video have an error on encoding? In the media library does it say that it's still a .mov file or does the media library show it as trauer-ein-gesellschaftliches-konstrukt.mp4 ?What is the shortcode you're using to embed the video? Does it happen to every video that's converted from another format to mp4 or only some?

**Comment by benhartwich** [comment]
Hi,

at my media lib it is shown  and registered as mp4. If I change the file link within the kgvid shortcode to mp4 there´s no error any more. It´s happening to all videos which are not encoded in mp4, but I´ve not tested every video codec. This video didn´t have any errors on encoding.

Also it´s strange, that some times not all entries automatically added to the queue are encoded. Sometimes the "custom h264 profile" isn´t encoded, sometimes the "Replace original with same resolution H.264 again". I don´t know why.

**Comment by kylegilman** [comment]
If WordPress is reporting the correct filename, how is the incorrect link in the shortcode generated? What is giving you the old filename?

Can you open another issue for your other issue? And let me know what status those unencoded formats are shown as in the queue.

**Comment by benhartwich** [comment]
The old filename comes from embedding the video after upload is completed and not if encoding is completed. Perhaps a mapping could help?

**Comment by kylegilman** [comment]
Right, but how are you "embedding" the old video file? Don't you have a template tag that does your embedding? Why isn't it generated dynamically using the current filename? Where is this old filename coming from? Is it some sort of custom meta field? If it was in the post content window it would be changed automatically, but there's something in your workflow I don't know about.

**Comment by benhartwich** [comment]
Ok,
the filename is stored by frontend uploader as mety key value to tm_video_file. 
At my custom header.php I insert a video file automatically:

<?php 
$file =  get_post_meta($post->ID, 'tm_video_file', true);
if ($file != NULL && !has_shortcode( $content, '[KGVID]') ) {
echo do_shortcode('[KGVID autoplay="true"]'.$file.'[/KGVID]');
} else {

This is all of my workflow.

**Comment by kylegilman** [comment]
That's what's causing the problem. Is your site set up so that you always have uploaded videos attached to the video post? If it is, I suspect that the `$file` variable is unnecessary and you can change the code to just this:

`echo do_shortcode('[KGVID autoplay="true"][/KGVID]');`

which will find any attached videos and embed them automatically. If there aren't any videos, nothing will be output. But that only works if the videos are attached to the posts you're embedding them in.

I'll also work on something that will catch problems like this.

**Comment by benhartwich** [comment]
Thanks, yes the file is attached everytime to the post, but the output is empty. I´ve tried it. Can this be caused when also the post image is attached to the post? I think it could be also related to the fact, that the shortcode isn´t placed within the wordpress loop.
I think I will wait until you´ve launched the feature.

**Comment by kylegilman** [comment]
Ugh. Yes, if it's outside the loop it won't get the video dynamically.

**Comment by benhartwich** [comment]
Can I build a custom loop with a few lines?

**Comment by kylegilman** [comment]
Can you test out this new modification? It worked for me outside of the loop with just `echo do_shortcode('[KGVID autoplay="true"][/KGVID]');`

**Comment by benhartwich** [comment]
No it doesn´t work. Have you really modified it?

**Comment by kylegilman** [comment]
Yes, I've really modified it. You can see the commit 9adefad 10 minutes ago on this issue.

**Comment by benhartwich** [comment]
Ah yes it works, I didn´t get it also to update the plugin.
