### ISSUE TITLE
DOMException when switching video quality manually

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#347]
Hi,

I get the following console error when I switch the video qualities manually: 
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

Is this anything I should care about?

Regards,

**Comment by kylegilman** [comment]
It's a problem recent versions of Video.js have when commands are executed very quickly. This one is caused by autoplay trying to play as soon as the video is switched. It shouldn't hurt anything, but I'll fix it anyway.
