### ISSUE TITLE
Seems to be pulling blank thumbs

### ISSUE THREAD

**Issue by Dragonsend** [kylegilman/video-embed-thumbnail-generator#352]
http://toontube.biz/wordtest/

More info. it seems to be uploading blank files to http://toontube.biz/wordtest/wp-content/uploads/temp/7.jpg WP setting maybe? 

same output for every vid... http://toontube.biz/wordtest/video_listing/test-new-plugin/attachment/7/
http://toontube.biz/wordtest/wp-content/uploads/temp/7.jpg 

Every video gets this attached, no thumbnail. Always temp folder always 7. Very weird. 

FFmpeg output. 

`FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers
  built on Jan 29 2012 17:52:15 with gcc 4.4.5 20110214 (Red Hat 4.4.5-6)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --enable-avfilter --enable-avfilter-lavf --enable-libdc1394 --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-librtmp --enable-libschroedinger --enable-libspeex --enable-libtheora --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab
  libavutil     50.15. 1 / 50.15. 1
  libavcodec    52.72. 2 / 52.72. 2
  libavformat   52.64. 2 / 52.64. 2
  libavdevice   52. 2. 0 / 52. 2. 0
  libavfilter    1.19. 0 /  1.19. 0
  libswscale     0.11. 0 /  0.11. 0
  libpostproc   51. 2. 0 / 51. 2. 0
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/toontube/public_html/wordtest/wp-content/plugins/video-embed-thumbnail-generator/images/sample-video-h264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.33.100
  Duration: 00:00:01.02, start: 0.000000, bitrate: 123 kb/s
    Stream #0.0(eng): Video: h264, yuv420p, 1920x1080 [PAR 1:1 DAR 16:9], 109 kb/s, 23.98 fps, 23.98 tbr, 11988 tbn, 47.95 tbc
    Stream #0.1(eng): Audio: aac, 48000 Hz, stereo, s16, 2 kb/s
[libx264 @ 0x1870b80]using SAR=1/1
[libx264 @ 0x1870b80]frame MB size (120x68) > level limit (1620)
[libx264 @ 0x1870b80]DPB size (1 frames, 3133440 bytes) > level limit (0 frames, 3110400 bytes)
[libx264 @ 0x1870b80]MB rate (195644) > level limit (40500)
[libx264 @ 0x1870b80]using cpu capabilities: MMX2 SSE2Fast SSSE3 FastShuffle SSE4.2
[libx264 @ 0x1870b80]profile Constrained Baseline, level 3.0
[libx264 @ 0x1870b80]264 - core 107 - H.264/MPEG-4 AVC codec - Copyleft 2003-2010 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 constrained_intra=0 bframes=0 weightp=0 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=abr mbtree=1 bitrate=6075 ratetol=0.7 qcomp=0.60 qpmin=10 qpmax=51 qpstep=4 vbv_maxrate=10000 vbv_bufsize=10000 ip_ratio=1.41 aq=1:1.00 nal_hrd=none
Output #0, mp4, to '/home/toontube/public_html/wordtest/wp-content/uploads/2016/07/sample-video-h264-fullres.mp4':
  Metadata:
    encoder         : Lavf52.64.2
    Stream #0.0(eng): Video: libx264, yuv420p, 1920x1080 [PAR 1:1 DAR 16:9], q=10-51, 6075 kb/s, 2997 tbn, 23.98 tbc
    Stream #0.1(eng): Audio: libfaac, 48000 Hz, stereo, s16, 128 kb/s
Stream mapping:
  Stream #0.0 -> #0.0
  Stream #0.1 -> #0.1
Press [q] to stop encoding
frame=   24 fps=  0 q=10.0 Lsize=      22kB time=0.92 bitrate= 195.5kbits/s
video:20kB audio:0kB global headers:0kB muxing overhead 8.625533%
[libx264 @ 0x1870b80]frame I:1     Avg QP:11.60  size: 13914
[libx264 @ 0x1870b80]frame P:23    Avg QP:10.95  size:   244
[libx264 @ 0x1870b80]mb I  I16..4: 97.7%  0.0%  2.3%
[libx264 @ 0x1870b80]mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.3%  0.0%  0.0%  0.0%  0.0%    skip:99.7%
[libx264 @ 0x1870b80]final ratefactor: -8.37
[libx264 @ 0x1870b80]coded y,uvDC,uvAC intra: 1.5% 0.0% 0.0% inter: 0.1% 0.0% 0.0%
[libx264 @ 0x1870b80]i16 v,h,dc,p: 98%  1%  2%  0%
[libx264 @ 0x1870b80]i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 37% 17% 25%  4%  2%  5%  2%  5%  2%
[libx264 @ 0x1870b80]i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x1870b80]kb/s:156.00`

**Comment by Dragonsend** [comment]
<img width="827" alt="captureplugin" src="https://cloud.githubusercontent.com/assets/20627124/17084969/2e90ea96-5181-11e6-8332-b2de0f735c54.PNG">

**Comment by kylegilman** [comment]
That is strange that the thumbnails are all called 7.jpg. I've never seen that before.
Have you tried disabling the option "When possible, use the browser's built-in video capabilities to make thumbnails instead of FFMPEG." on the FFMPEG Settings tab? Does that make a difference?
Are the videos all the same filename? 
Are there any unusual characters in the video filenames? 
Are you manually generating the thumbnails or are they generated automatically on upload? 
How many thumbnails are you generating at a time?

**Comment by Dragonsend** [comment]
I have tried When possible, use the browser's built-in video capabilities to make thumbnails instead of FFMPEG." on the FFMPEG Settings tab? Does that make a difference?
it does not seem to. 
No the videos are not the same filename. 
Not unusual characters in the names. 
I would like them auto generated on upload. Do not want manual
I was trying to do more than 1. Let me try just doing 1 to see if that helps. 

No it didn't help just setting it to one. 
I reset the options then set them so there were no baseline errors etc in the output 
Wanted to see if i had something set wrong. 
uploading a test video now.

**Comment by Dragonsend** [comment]
Now it doesn't seem to attach anything.

**Comment by Dragonsend** [comment]
Could it be the theme itself? Now the video upload option on the theme isn't working at all.

**Comment by Dragonsend** [comment]
K When I enable jetpack. It seems to cause this on the Video Craft theme. I found that issue. i just want a theme that lets users upload videos. At this point I'm thinking it might be the theme. I can give you admin access if you want to look at the settings. If you feel it isthe theme as well just stir me in the right direction to get one that works and generates thumbnails for users. I didn't realize it was so difficult. While i do not have a lot of money i will donate at least 20 bucks to you Wednesday for your help. That is only right.

**Comment by Dragonsend** [comment]
So i disabled nearly every plugin in there. it is doing the weird generating a 7 thing again. 
<img width="800" alt="captureweirdneess2" src="https://cloud.githubusercontent.com/assets/20627124/17086027/78d3b2bc-519c-11e6-8cb8-1dcda82c60f1.PNG">

**Comment by kylegilman** [comment]
Yes, I think it's your theme. Your theme has some sort of custom "Video" object that doesn't work the way normal videos work in WordPress. I tried uploading a clip using the regular Media upload system in WordPress and it worked fine.

**Comment by Dragonsend** [comment]
Thank you very much for your help. This was the Video Craft Theme from ink themes in case anyone wanted to know.

**Comment by Dragonsend** [comment]
I will donate to your plugin Wednesday when I get paid. Thank you so very much for your time. I greatly appreciate it. 

Jess
