### ISSUE TITLE
embedding <iframe> on iOS w/ JW Player doesn't stop resizing

### ISSUE THREAD

**Issue by n0risc** [kylegilman/video-embed-thumbnail-generator#355]
When I embed video in an iframe, rendering on iOS devices the frame continually zooms indefinitely until it crashes the safari browser.

**Comment by kylegilman** [comment]
My plugin doesn't do any resizing when you're using JW Player. I can't duplicate this issue on my own site. Can you post a link to a page demonstrating the problem?

**Comment by kylegilman** [comment]
Closing old support issues. If you're still experiencing a problem please open a new issue.
