### ISSUE TITLE
Nativecontrolsfortouch has double controls on Android

### ISSUE THREAD

**Issue by kylegilman** [kylegilman/video-embed-thumbnail-generator#358]
https://wordpress.org/support/topic/two-issues-heightwidth-shortcode-does-not-work-double-controller-on-andriod/

**Comment by panshengjie** [comment]
I got this too.
no double controls when there is only one resolution, which indicates it has something relates to the resolution-selector

**Comment by kylegilman** [comment]
Seems to be fixed now.
