### ISSUE TITLE
fullscreen broken in wordpress default way

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#359]
in chrome: 
in wordpress default way , click fullscreen when the video has not be played, fullscreen will broken 

video.js and flash mode works well

**Comment by kylegilman** [comment]
I can't duplicate this issue on my own site. Can you post a link to a page on your site that demonstrates the problem?

**Comment by panshengjie** [comment]
I set up a test page for you:
http://pandaserver.jios.org:81/test-for-video/
the server is China ,my home , so it maybe slow for you

**Comment by kylegilman** [comment]
This might be caused by your theme. As a test, try using the built-in WordPress shortcode`[video width="720" height="1080" mp4="http://pandaserver.jios.org:81/wp-content/uploads/2016/09/V60918-094738.mp4" preload="none"]' and see if you have the same problem.

**Comment by panshengjie** [comment]
yes, it should be the theme problem.   thanks for you inspection.

**Comment by panshengjie** [comment]
I just checked this problem, and find it was the mediaelement.js bug
lucky, the bug just fix last month at [here](https://github.com/johndyer/mediaelement/pull/1811)by just replace one line code.
I just upgrade to it's latest build, it's fine now.
it should help your customer if you raise a note of upgrading mediaelement.js when user choose wp default mode.
the issue should close now.
