### ISSUE TITLE
change resolution failed  in wordpress default way

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#360]
when change resolution  in wordpress default way , video paused waiting for 'canplay' event, however that won't fire in chrome. so the video stuck. 
and when I check into the network, there is no load data after change resolution

**Comment by kylegilman** [comment]
I can't duplicate this issue on my own site. Can you post a link to a page on your site that demonstrates the problem?

**Comment by panshengjie** [comment]
I set up a test page for you:
http://pandaserver.jios.org:81/test-for-video/
the server is China ,my home , so it maybe slow for you

**Comment by kylegilman** [comment]
I see. Since you've set preload to none, the video element doesn't load the metadata and never starts the video. I'll have to add a check for preload set to none.
