### ISSUE TITLE
file path/name support for chinese video 

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#364]
current version is not support for chinese video(in name).
when I upload file 测试.mp4, the plugin is not able to read file, error:
`Can't open movie file.
libpostproc 54. 0.100 / 54. 0.100
/XXX/wordpress/htdocs/wp-content/uploads/2016/10/.mp4: No such file or directory` 

it indicates  pulgin only allow video named in pure english, NO chinese japanese etc.
maybe urldecode() will help

**Comment by kylegilman** [comment]
I can't duplicate this error. I uploaded a file called 测试.mp4 and I'm able to make thumbnails and encode videos. I'm aware of a number of users that use non-Latin characters in their filenames without trouble. The only problem I know about is that [some Windows servers have trouble with Arabic character encoding](https://github.com/kylegilman/video-embed-thumbnail-generator/issues/246) but I don't think they have the same problem with Chinese characters. What OS and web server software are you running?

**Comment by panshengjie** [comment]
I test it again, still can't open movie file. but the video can play via medialibaray view.
I have to do more test to inspect.

**Comment by panshengjie** [comment]
maybe I got it
in video-embed-thumbnail-generator.php line 5233
`wp_schedule_single_event( time() + rand(0,10), 'kgvid_cron_new_attachment', array($post_id) );`
require accurate wp cron, which didn't fit my system with cron per minute;

I copy video-embed-thumbnail-generator.php in the github into my plugin floder, no more " Can't open movie file" error but thumbnail remains in "Loading thumbnail..."  when kgvid_cron_new_attachment is not called yet. after kgvid_cron_new_attachment is called ,all goes right.

**Comment by panshengjie** [comment]
this issue is quite weird
I revert video-embed-thumbnail-generator.php into 4.6.12 and no more " Can't open movie file" but "Loading thumbnail..." and wait to for some seconds all goes right. 
I can't duplicate " Can't open movie file"  now, that's weird.
to my experience, there should be something wrong deep, but can't caught it
leave it if no more error

**Comment by panshengjie** [comment]
the problem is still there, I will fix it when I get time.

**Comment by panshengjie** [comment]
recently I fixed a similar problem in wp: when upload a chinese name file, the title section in wp medialib failed to recognize the original chinese name but replaced with unicode .  I fix this by add urldecode() somewhere in media.php

after this , the issue here seems ok now.

**Comment by kylegilman** [comment]
You should [report this bug to WordPress](https://make.wordpress.org/core/handbook/testing/reporting-bugs/) if it's a core problem.
