### ISSUE TITLE
video encode queue "replace original" abnormal

### ISSUE THREAD

**Issue by panshengjie** [kylegilman/video-embed-thumbnail-generator#365]
if I encode(ffmpeg) a big video (1080p) in the order: 
1, replace original ;
2, 720p;
3, 360p
It has a great possibility 'replace original' will fail when new video replacing the old but find the old file cannot delete (probably because decoding 720p); what's worst, the new encoded video deleted.
another possibility is the video is successful replaced, but the database not refresh, so 720p and 360p will not encode because file not found.

additional info is that  my wp cron runs per minute by using a cron plugin, I wonder if relacing old video requires accurate cron. anyway, we should not require user's wp cron to be accurate.

**Comment by kylegilman** [comment]
"Accurate" cron and WordPress are not things that go together and I certainly don't rely on cron timing for this process. The plugin is supposed to wait until all videos are finished encoding before the replacement process happens. But just for troubleshooting purposes, have you tried disabling the cron plugin to see if you have the same problem?

**Comment by panshengjie** [comment]
this problem occurs a lot , I have to encode manually for several times to get all videos done.
I gonna test more to provide more info

**Comment by kylegilman** [comment]
That narrows it down a lot, and should make it a simple fix. Does this only happen when you press the update button?
