### ISSUE TITLE
Pagination is not working in current build

### ISSUE THREAD

**Issue by abhishekshankar** [kylegilman/video-embed-thumbnail-generator#366]
Pagination is not working in current build

**Comment by kylegilman** [comment]
Thanks, I assume you're referring to gallery pagination? [Another user pointed this out in the WordPress forums.](https://wordpress.org/support/topic/pagination-not-working-114/) I've [fixed it in Github](https://github.com/kylegilman/video-embed-thumbnail-generator/commit/959c6d037a31b5051e3e9376f9bda2d9ae0e7bef), but haven't had the time to finish the latest release. I'll have it out soon. If you are comfortable using an unreleased version, feel free to download the current Github code.
