### ISSUE TITLE
Auto encoding does not start

### ISSUE THREAD

**Issue by ManuTeMaia** [kylegilman/video-embed-thumbnail-generator#370]
Hello!
Great and very helpful plugin! Thank you! 
But there is one issue. After uploading a .mov file auto encoding does not start and video does not append to the queue (see the screenshots below)
![2016-11-04 01 47 18 am](https://cloud.githubusercontent.com/assets/20460790/19988382/cfaccff8-a230-11e6-94f7-6cd9b2e667bf.png)
and there is the settings
![2016-11-04 01 48 04 am](https://cloud.githubusercontent.com/assets/20460790/19988383/cfb2766a-a230-11e6-8254-36c57bdd3048.png)
There are no relevant errors in the wordpress debug.log or in the appache error.log...

q: Any ideas how to fix it? Thank you in advance!

**Comment by kylegilman** [comment]
Do you have any plugins that modify the execution of WP-Cron? If you manually add a couple videos to the queue does the 2nd video start encoding even if the encoding queue page isn't open?

**Comment by ManuTeMaia** [comment]
oh, sorry for delay
my e-mail server have been fall down for several days (

It’s OK now with cron & queue - the problem was in hosting provider’s apache settings. Now auto encoding works perfectly! Thank you again for your work!

I have one more question. How can I hide plugin's meta fields in media library for certain user role?  I won’t like to use a css/js hiding but wp hooks like «remove_meta_box» doesn’t work. Can I alter your plugin files somehow or add some add. code in functions.php?  Thank you!

**Comment by kylegilman** [comment]
Do you know specifically what those Apache settings were? It would be a big help for future users who have this problem.

The plugin settings page allows you to disable video encoding or thumbnail generation for specific user roles. The meta fields are still visible in that case, but they're read-only. What specific information do you think should be hidden from users and not just disabled?

**Comment by ManuTeMaia** [comment]
First, I install WP Crontrol plugin and at last find an error: "There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was: 
cURL error 28: Connection timed out after 3001 milliseconds»
Trying to find a solution I 
1) wrote to the hosting admins (had no reply from them though) 
2) add to wp-config.php this code: define( 'ALTERNATE_WP_CRON', true ); (in somewhere in the the middle of the file, as I read it’s important somehow…)
So… after these actions wp-cron became alive and kicking. But I really doubt that the altering of wp-config.php had made any sense…  It might be so, but it’s strange -  I’ve never seen this type of errors in my other hostings with Wordpress sites (including my own Centos server). I suspect some wrong directives in virtual host settings or troubles with memory allocation on the web-server. Anyway, admins didn’t answer me yet regarding this error and the ways they resolved it, and whether they did anything at all? :)


Back to my question, I have a case: the customer is really not-friendly with any web interfaces and he demands «one-button» interface (or «simple-like-facebook» interface) to make posts with photo & video in his wordpress blog via his iPad. As we now have an auto encoding + auto thumbnail I think it was a good idea to hide all meta boxes (except Name & Caption may be) from the customer’s eyes so as not to frighten him )) 

Best Regards, Ekaterina

**Comment by kylegilman** [comment]
Thanks for the info about WP-Cron. I rely on it for a lot of the more complicated features of the plugin but it's very difficult to make it work on the many possible server setups my users might have.

The plugin uses `attachment_fields_to_edit` to add to an array of fields. To remove all custom fields from video attachments, you could try adding a function like this (not tested. Use at your own risk)

```
function remove_kgvid_custom_fields($form_fields, $post) {

	global $user

	if ( array_key_exists('kgflashmediaplayer-security', $form_fields) //if one of the custom fields is set
		&& !current_user_can('see_video_attachment_details')  //and the current user doesn't have permission to see it. Change this to whatever user capability you want.
	) {  

		$form_fields = array(); //clear all custom form fields

	}

	return $form_fields;

}
add_filter("attachment_fields_to_edit", "remove_kgvid_custom_fields", 11, 2);
```

I'm not positive this will have the right effect, but it should point you in the right direction.

**Comment by ManuTeMaia** [comment]
Hi, Kyle,

Thanks for the code!
!’ve altered it a bit for my needs. Works perfectly!
=============
if (!function_exists ('get_current_user_role')) {
	function get_current_user_role() {
	global $wp_roles;
	$current_user = wp_get_current_user();
	$roles = $current_user->roles;
	$role = array_shift($roles);
	return $wp_roles->role_names[$role];
}
    
}
	
	function remove_kgvid_custom_fields($form_fields, $post) {

    global $user;
    $current_user_role = get_current_user_role();
    if ( array_key_exists('kgflashmediaplayer-security', $form_fields) //if one of the custom fields is set
        && $current_user_role=='Author'  //and the current user doesn't have permission to see it. Change this to whatever user capability you want.
    ) {  

        $form_fields = array(); //clear all custom form fields

    }

    return $form_fields;

}
add_filter("attachment_fields_to_edit", "remove_kgvid_custom_fields", 11, 2);
==================

Ekaterina

**Comment by kylegilman** [comment]
Great! Glad I could help out.
