### ISSUE TITLE
No attachment URL generated after the video upload

### ISSUE THREAD

**Issue by vladmirom** [kylegilman/video-embed-thumbnail-generator#378]
When I upload video there's no path to that file written in the database. Thus, video is not showing on the front-end. 
There's no video sample in the settings as well: 

<img width="852" alt="screenshot at 19 15-45-27" src="https://cloud.githubusercontent.com/assets/13310180/22108983/54a30740-de5e-11e6-8d34-75945f7a780b.png">

This issue has appeared after the latest updates.

**Comment by kylegilman** [comment]
Just to help me narrow it down, the latest updates meaning the update from 2 weeks ago or the development version on Github I just made a bunch of changes to over the past few days?

Are you using a CDN like Amazon S3? Or a frontend uploader? Does your site support SSL? Which path to the file isn't written in the database? Is it _wp_attached_file? Is that field empty or just doesn't exist? Have you tried disabling other plugins to make sure there isn't a conflict?
