### ISSUE TITLE
Video views are not counted when quarter-counting is enabled

### ISSUE THREAD

**Issue by kylegilman** [kylegilman/video-embed-thumbnail-generator#381]

**Comment by n0risc** [comment]
Works on start/complete... But  start/25/50/75/complete. It does not count.

Goldy.

**Comment by kylegilman** [comment]
Thanks @n0risc !

**Comment by n0risc** [comment]
Strangely, all sites that were already configured still count the views on the old default setting which was  start/25/50/75/complete..   However, new sites with 4.6.16, count views as the default is  start/complete and when switched to the old default, it stops counting.  More research into it for your Kyle.

**Comment by n0risc** [comment]
Guessing it's not storing the setting correctly in database/settings.

**Comment by kylegilman** [comment]
Yeah, the setting had two different names depending on whether you upgraded or made a new installation. Thanks again. That explains why nobody had complained about it, since it was only happening to new users.
