### ISSUE TITLE
Automatic reload of Encoding Queue

### ISSUE THREAD

**Issue by benhartwich** [kylegilman/video-embed-thumbnail-generator#393]
Hi,

sometimes encodings stuck in the process after they were cued automatically. When I visit the page Video Embed & Thumbnail Generator Encoding Queue the encoding process is restarted. Is there any way to create a php cronjob to trigger this process every 15 minute if there is something which has interrupt the encoding?

**Comment by kylegilman** [comment]
I think I see where I can fix this. From what I can tell, if a user never actually sees the encoding start on either the attachment details page or the encode queue, the plugin doesn't start a wp-cron job to check on the progress which means the next video never starts until you go to the encode queue page.
