### ISSUE TITLE
FFMPEG triggered every time I go to media library page with video

### ISSUE THREAD

**Issue by baderatw** [kylegilman/video-embed-thumbnail-generator#396]
All of the videos have been converted, there's nothing in the queue.  But every time I hit a page in my media library that has a video listed - ffmpeg is triggered and consumes all of the disk space with files in /tmp

**Comment by kylegilman** [comment]
I haven't heard of that happening before. Is there anything unusual about your server setup? Even if nothing shows up on the Video Encode Queue, have you tried clicking the "Clear All" action at the bottom of the queue? Does that have any effect? Are you able to get any logs to determine what FFMPEG thinks it's accomplishing?

**Comment by baderatw** [comment]
nothing unusual, pretty typical centos6/lamp setup... and it had been working fine previously, I will try clear all and let you know

**Comment by baderatw** [comment]
Closed, plugin conflict

**Comment by kylegilman** [comment]
Woah. Which plugin? That's important for me to know about.

**Comment by baderatw** [comment]
Regenerate ThumbnailsActivate \| Delete | Regenerate the thumbnails for one or more of your image uploads. Useful when changing their sizes or your theme.Version 3.0.1 \| By Alex Mills (Viper007Bond) \| Visit plugin site
-- | --

**Comment by kylegilman** [comment]
Thanks. That's a really popular plugin so I'm going to try to get to the bottom of the conflict.

**Comment by baderatw** [comment]
May be on their end - it was triggering ffmpeg on any admin page with video thumbnails, and ghostscript on any admin page with pdf thumbnails
