### ISSUE TITLE
Video Gallery Height

### ISSUE THREAD

**Issue by dmkjr** [kylegilman/video-embed-thumbnail-generator#399]
I'm have set a height="XXX" attribute in the shortcode, but our videos on this page are still showing up not uniform.  I understand one video is landscape and one video is portrait, but I thought through the settings and especially the height attribute, I could level that out.

https://cityofhanahan.com/galleries/midnight-basketball/

**Comment by kylegilman** [comment]
The height attribute doesn't affect video gallery thumbnails, only individual video players. The plugin doesn't have any settings to constrain video gallery thumbnail aspect ratios. If you crop the portrait-oriented thumbnail to 16:9 aspect ratio yourself that should solve the problem.

**Comment by dmkjr** [comment]
Thanks.  Does your plugin offer the ability to crop that thumbnail?

**Comment by kylegilman** [comment]
WordPress has that function built in. https://enviragallery.com/how-to-edit-images-in-wordpress/
