### ISSUE TITLE
Video img title issue

### ISSUE THREAD

**Issue by edmondoddy** [kylegilman/video-embed-thumbnail-generator#407]
Hi,

I see video image title set to title="To view this video please enable JavaScript, and consider upgrading to a web browser that supports HTML5 video"

Could you please help me to fix this?

Check the screenshot please, Thanks

https://imgur.com/a/D9Ba6sR

**Comment by kylegilman** [comment]
My plugin doesn't generate that code. It looks to me like you're using something called Boombox Featured Video to embed your video.
