### ISSUE TITLE
Vp9 file conversion failed!

### ISSUE THREAD

**Issue by edmondoddy** [kylegilman/video-embed-thumbnail-generator#420]
Hi, when I upload a mov file I get vp9 file conversion failed, vp8 and mp4 files created successfully on automatic, could you please check the txt file to tell me what is the problem about? 

[file_example_MOV_1280_1_4MB-2_vp9_0965_encode.txt](https://github.com/kylegilman/video-embed-thumbnail-generator/files/2664219/file_example_MOV_1280_1_4MB-2_vp9_0965_encode.txt)

Latest ffmpeg installed.

Thanks

**Comment by kylegilman** [comment]
This is only for .mov files? Other files work without this error?

**Comment by edmondoddy** [comment]
Yes, only mov files

**Comment by kylegilman** [comment]
Do you get this problem with all mov files or just one in particular? I can't replicate this error with my three-year-old installation of FFMPEG.
