### ISSUE TITLE
Add custom VP9 & How to add few custom formats?

### ISSUE THREAD

**Issue by edmondoddy** [kylegilman/video-embed-thumbnail-generator#422]
Hi, how to add a few custom formats?

I see only 1 custom format checkbox in the plugin page, would like to add few more.
Would be great if you can help me with it :)

Another thing, when I convert a video to WebM custom format I see the file got Codec VP8, there is no way to convert videos to custom format webm but VP9?

Thanks

**Comment by kylegilman** [comment]
I'm working on a system to modularize the formats and allow plugins to modify or create new ones in #414 
It looks like I forgot to add a VP9 custom format option.

**Comment by edmondoddy** [comment]
btw I have tried the 4.6.22 version, with same setting like I got on 4.6.21 but the move file and mp4 get broken, I didnt saw the reports, just reverted back to 4.6.21 and it works fine...

just let you know

**Comment by edmondoddy** [comment]
I can do tests if you can do updates, just let you know, I see got a week before releasing the project I am working on.

Would be great if you can work on it, I can do test asap if needed I mean :)

**Comment by kylegilman** [comment]
Yeah, there's a reason 4.6.22 isn't released yet. It doesn't work. And it probably won't be finished next week.

**Comment by kylegilman** [comment]
Custom VP9 is using VP8 CRF. Should revisit tying VP9 CRF to H.264 CRF. [Google recommends](https://developers.google.com/media/vp9/settings/vod/) different values for different resolutions.

**Comment by kylegilman** [comment]
@edmondoddy if you want to test out the current version on Github I think custom VP9 encoding is working now. And I can help you build a plugin to make multiple custom formats.
