### ISSUE TITLE
Remove the ID=?

### ISSUE THREAD

**Issue by talkmatoh** [kylegilman/video-embed-thumbnail-generator#444]
So when u use the KGVID the code is shown like this:

<video id=”video_kgvid_0″ controls preload=”metadata” width=”1920″ height=”1080″ class=”fitvidsignore video-js kg-video-js-skin”>
<source src=”http://site.net/1.mp4?id=0″ type=”video/mp4″ data-res=”Full”>
</video>
And it add itself a id to the video with a number, Can I know is it possible to remove that “?id=0” some how?

**Comment by kylegilman** [comment]
You could edit the code to remove it, but you'd have to do that every time you updated the plugin. Can you explain what you're trying to accomplish that removing the query string would help with?

**Comment by talkmatoh** [comment]
Well that works fine with normal source like .mp4 extension but when u use it on vides that are accessed with token authentication it dosnt work, can u please tell me which lines shoud I edit on the code for that?

**Comment by kylegilman** [comment]
I think a better solution would be for me to avoid adding query strings to URLs that already have them.

**Comment by talkmatoh** [comment]
Yea that woud be better I guess like the URLS that have other strings after .mp4 to dont have the ID= after added, can u help me remove this for now?

**Comment by kylegilman** [comment]
Assuming you're using Video.js find this line in video-embed-thumbnail-generator.php

`$sources[$source_key] = "\t\t\t\t\t".'<source src="'.esc_attr($encodevideo_info[$format]["url"]).'?id='.$kgvid_video_id.'" type="'.$format_stats["mime"].'"';`

Change it to:
`$sources[$source_key] = "\t\t\t\t\t".'<source src="'.esc_attr($encodevideo_info[$format]["url"]).'" type="'.$format_stats["mime"].'"';`

**Comment by talkmatoh** [comment]
That worked thank you very much, so on next update I might have to edit this again right?

**Comment by kylegilman** [comment]
I just committed a change 995a39dc65840bc4e0fe486804d6f8314042febe which should fix the problem for you on the next update without having to make the edit again but if you find the problem comes back please let me know.
