### ISSUE TITLE
Store URL on the plugin?

### ISSUE THREAD

**Issue by talkmatoh** [kylegilman/video-embed-thumbnail-generator#449]
Hello I wanted to know is it possible to store the video url on the plugin php? 
So when I want to call it I just do something like echo $videourl; ? Is such thing possible as I might need to change video url but not the path so coud it be possible to change the url of all videos at once from the plugin?

**Comment by kylegilman** [comment]
If you're embedding videos where the URL might change in the future, you might want to just use the shortcode on its own: `[KGVID][/KGVID]` will automatically embed any videos attached to the current post. If you need more control over what gets embedded, you could use the video's ID which won't change when you change URLs: `[KGVID id='123'][/KGVID]`

**Comment by talkmatoh** [comment]
I dont think u understand this is what my embed video is right now:
[KGVID]http://website.com/video.mp4[/KGVID]
But I have many embed videos on my site and on future the website.com might change so I dont go manually changing that for all to something like website.net I'm asking is it possible to store website.com somewhere on the plugin and then when I add I video I just do something like [KGVID] echo $videourl[/KGVID]

**Comment by kylegilman** [comment]
You can use a plugin like [Velvet Blues Update URLs](https://wordpress.org/plugins/velvet-blues-update-urls/) for changing URLs that are already embedded.

**Comment by talkmatoh** [comment]
Dosnt work somehow for me

**Comment by talkmatoh** [comment]
I think that dosnt work for widgets maybe only for posts

**Comment by kylegilman** [comment]
So you have many videos on your site embedded via shortcodes in widgets? Can you post a link to your site? I need to get a better handle on the problem. I think there might be a way to assign a filter to URLs that are sent to the plugin so you can find and replace parts of the URL dynamically.

**Comment by talkmatoh** [comment]
Using this https://wordpress.org/plugins/enhanced-text-widget/
To add the videos as a widget

**Comment by kylegilman** [comment]
I just added a filter to the 4.6 branch on Github which you can download here https://github.com/kylegilman/video-embed-thumbnail-generator/archive/4.6.zip

Install that and then make a custom plugin for your particular URL rewriting needs:

```php
<?php
/*
Plugin Name: Videopack URL Renamer
Description: Renames URLs in existing KGVID shortcodes
Version: 0.1
Author: Kyle Gilman
Author URI: https://www.kylegilman.net/
*/

function videopack_filter_url($url) {

    $url = str_replace('oldurl.com', 'newurl.net', $url);
    return $url;

}
add_filter('kgvid_filter_url', 'videopack_filter_url');
```

Change 'oldurl.com' to your old URL and 'newurl.net' to your new URL

**Comment by kylegilman** [comment]
Or use this file
[videopack-url-renamer.zip](https://github.com/kylegilman/video-embed-thumbnail-generator/files/3273172/videopack-url-renamer.zip)

**Comment by talkmatoh** [comment]
> Or use this file
> [videopack-url-renamer.zip](https://github.com/kylegilman/video-embed-thumbnail-generator/files/3273172/videopack-url-renamer.zip)

That works but is it possible somehow to include like sort of text like $text on the plugin and then recall it when I use [KGVID] I'm asking this beacuse I'm using some sort of token authenticator for this and if I want to change the token I woud like to just change it on plugin let says where it stored not manually each video.

**Comment by kylegilman** [comment]
I do not understand what you are asking for.
