### ISSUE TITLE
global $user_ID is NULL even if user is logged in

### ISSUE THREAD

**Issue by tamara-m** [kylegilman/video-embed-thumbnail-generator#453]
This is a weird one but hopefully an easy fix too.
I have the plugin installed on two other sites, a live and a dev version, and everything works fine.
We are now building an exact duplicate of this site, just a different branding, and even though all options, permissions, themes, plugins and version are all exactly the same, on the new site, the "Choose from video" player and thumbnail selection button are not displaying for the roles it should, just the admin.

I tracked down the issue to function `kgvid_image_attachment_fields_to_edit` and specifically the check `if ( $user_ID == $post->post_author || current_user_can('edit_others_posts') )`

The `$post` data is perfect in all cases, however, for some reason the global $User_ID is `NULL` in the new site even if the user is in fact logged in. 

If I add `$user_ID = get_current_user_id();` after the NULL `global $user_ID;` everything works perfectly across the board as expected. 

Wondering if there was any way that I can provide the current user id instead of using the global, as I don¡t want to modify your core files. 
Or if you'd be open to modifying your fetching of the user id  to additionally checking `get_current_user_id()` in case the global is null?

Something like 

```
if( !isset($user_ID) && is_user_logged_in() ){
     $user_ID = get_current_user_id();
}
```
 
Thank you in advance for your time and consideration.

**Comment by kylegilman** [comment]
Oh that's some bad programming on my part. Relying on a global variable that isn't always available. This is one of those things that's probably been in the plugin for many years and I never went back and looked at it. I'll change all the uses of the supposed global variable $user_ID in the next release.
