### ISSUE TITLE
Upgrading WP Core removes queue in Tools menu

### ISSUE THREAD

**Issue by cmseal** [kylegilman/video-embed-thumbnail-generator#458]
Going from 4.9 to 5.3, the Video Encode Queue is now gone from the Tools menu.

I've tried using the URL manually, but it tells me I don't have permission to view the page.

Any suggestions?

Many thanks!

**Comment by kylegilman** [comment]
It sounds like the plugin settings were corrupted. Go to the FFMPEG Settings tab on the plugin settings page and change the "Path to applications folder on the server" setting to something else, save settings, then change it to the correct path. If that doesn't work you might need to hit the Reset options button at the bottom of the page.

**Comment by cmseal** [comment]
Thanks for the swift reply. To clarify, the menu only seems to have disappeared doing a larger jump.  An incremental update of core from 4.9.13 to 5.3.2, via 5.0.8, 5.1.4 and 5.2.5.
