### ISSUE TITLE
PHP Warning:  array_key_exists()

### ISSUE THREAD

**Issue by endyb66** [kylegilman/video-embed-thumbnail-generator#459]
I got the following error inside my apache error logfile:

`PHP Warning:  array_key_exists() expects parameter 2 to be array, string given in /var/www/html/wordpress/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 3231`

**Comment by kylegilman** [comment]
I guess some other stuff was going on in March 2020 but I missed this until now. Thanks for reporting it.
