### ISSUE TITLE
Videopack plugin causes trouble with the Woocommerce import (only the image url goes wrong)

### ISSUE THREAD

**Issue by YuthBKK** [kylegilman/video-embed-thumbnail-generator#482]
Dear Kylegilman,
I truly appreciate your marvelous plugin. It works really well. But I realize later that it causes Image URL import in Woocommerce to fail. If I import with file "Test.csv", the image URL will become "test.csv", or the name of file that I upload. 
The import will work as usual, after I deactivate the Videopack plugin.  (I found the fix by deactivating the plugin one by one to see which one causes the issue)
I guess it must be some kinds of conflict with Woocommerce Import suites. It would be great if it can be fixed.
Best regards,
Yuth

**Comment by kylegilman** [comment]
Thanks for posting this. I recently solved a larger issue with Woocommerce image importing https://wordpress.org/support/topic/once-enable-the-plugin-woocommerce-cannot-use-csv-import-function/ but I didn't realize the image URL was coming in wrong.

**Comment by kylegilman** [comment]
Sorry I haven't gotten to this until now but I can't duplicate the error. I'm using the sample_products.csv file that comes with Woocommerce to import products and those images are importing. Where do you see the image URL changing to the CSV filename? I don't know a lot about Woocommerce so I might be doing the wrong kind of import? Do you have a particular CSV file you can upload that demonstrates the problem?
