### ISSUE TITLE
`RuntimeException: Unable to launch a new process` on updating from 4.7.* to 4.8.*

### ISSUE THREAD

**Issue by sulfo** [kylegilman/video-embed-thumbnail-generator#505]
Hello.

I tried to update the plugin, but I'm met with an uncaught RuntimeException, and the only way to recover the WordPress installation is to temporarily rename the plugin folder, to force WordPress to disable the plugin.

Here's the stack trace from the error:
```
Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: Unable to launch a new process. in /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/vendor/symfony/process/Process.php:355 
Stack trace: 
#0 /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/vendor/symfony/process/Process.php(252): Symfony\Component\Process\Process->start(NULL, Array) 
#1 /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php(1069): Symfony\Component\Process\Process->run() 
#2 /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php(1414): kgvid_ProcessThumb('/nas/content/li...', '/nas/content/li...', '/usr/local/bin/...') 
#3 /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php(6385): kgvid_check_ffmpeg_exists(Array, true) 
#4 /nas/content/live/website/wp-includes/class-wp-hook.php(308): kgvid_update_settings('') 
#5 /nas/content/live/website/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) 
#6 /nas/content/live/website/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#7 /nas/content/live/website/wp-settings.php(617): do_action('init') 
#8 /nas/content/live/website/wp-config.php(120): require_once('/nas/content/li...') 
#9 /nas/content/live/website/wp-load.php(50): require_once('/nas/content/li...') 
#10 /nas/content/live/website/wp-blog-header.php(13): require_once('/nas/content/li...') 
#11 /nas/content/live/website/index.php(17): require('/nas/content/li...') 
#12 {main} thrown in /nas/content/live/website/wp-content/plugins/video-embed-thumbnail-generator/vendor/symfony/process/Process.php on line 355
```

I'm not sure why this accrues, but I hope you might know what the issue is caused by.

**Comment by kylegilman** [comment]
Thanks for bringing this to my attention. Do you have FFMPEG on your server and have you been using my plugin to make thumbnails or encode videos in v4.7?

**Comment by sulfo** [comment]
I've been in touch with WP Engine support, and FFMPEG is not installed.
We use 4.7.5 for everything - except the video encoding part.

So that's thumbnails, change the default videoplayer. 👍

**Comment by kylegilman** [comment]
Looks like you have two copies of the plugin in your wp-content/plugins folder. You'll need to deactivate the one in the /video-embed-thumbnail-generator-4.7.5/ first.

**Comment by sulfo** [comment]
> Looks like you have two copies of the plugin in your wp-content/plugins folder. You'll need to deactivate the one in the /video-embed-thumbnail-generator-4.7.5/ first.

Oh! My bad.
4.8.3 is working so far without any issues 👍

Thanks for fixing it so fast 🙌

**Comment by kylegilman** [comment]
Great! Thanks for testing it out too.
