### ISSUE TITLE
Video Pack Fatal Issue: Warning: Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by mykkal** [kylegilman/video-embed-thumbnail-generator#519]
My apologies. I tried emailing you about this. I found the issue but cannot fix it myself.

I'm getting errors returned from videopack that cause the site to crash from time to time. The video queue stays empty and no videos are converted.

The error is: `Warning: Invalid argument supplied for foreach() in /****/****/public_html/wp-content/plugins/video-embed-thumbnail-generator/src/admin/videopack-ffmpeg.php on line 2528`

I found an article that explains a fix for this issue: [educative.io/answers/fixing-the-invalid-argument-supplied-for-foreach-php-error](http://educative.io/answers/fixing-the-invalid-argument-supplied-for-foreach-php-error)

Would really appreciate the help or work around if you have one.

This is affecting https://ironpalmtattoos.com

**Comment by kylegilman** [comment]
Somehow your video encode queue has a value in it that's not empty and not an array. I'll have to do some digging to figure out how that could happen. But in the meantime I'll add a check to make sure it's an array before starting the foreach loop. I'll try to get an update out soon.

**Comment by mykkal** [comment]
Much appreciated. 
Do you think it could be due to data corruption?

If you need access to the installation please let me know. Any idea when you'd planned to release the next version?

I do appreciate your work Kyle. You have a very mature product. Hopefully you won't have to deal with bugs soon.

**Comment by kylegilman** [comment]
Ha! There will always be more bugs. I just put out an update that I hope will solve this bug though.

**Comment by mykkal** [comment]
Bug seems to be back. Am now getting.

`Warning: foreach() argument must be of type array|object, string given in /home/ironpalm/public_html/wp-content/plugins/video-embed-thumbnail-generator/src/admin/videopack-ffmpeg.php on line 1590
`

**Comment by kylegilman** [comment]
I made more thorough checks to avoid that error, but I'd love to know what the string is in your encode queue. Are you able to look in your database to see what the 'kgvid_video_embed_queue' entry is in the wp_options table?

**Comment by mykkal** [comment]
I couldn't post all of it. I'm not sure its been working at all.

**Comment by kylegilman** [comment]
It's a good idea to avoid posting your full server path publicly. I deleted the data, but it was the beginning of what looked like a normal serially encoded array.
Without the whole array I can't tell what's causing the problem, but it's possible your queue is so big that it's running out of room to save the whole thing and so when it's read, it can't be unserialized and turned into an array. Can you try pasting the whole thing here? https://www.unserialize.com/ See if that gives you an error.

**Comment by mykkal** [comment]
I'll be happy to do that for you. Is there no scalable way to handle large
queue? I actually don't have that many videos uploaded so i'm a little
confused. I think that wpcron isn't running however.
--
Mike McKoy
770-203-8805

**Comment by mykkal** [comment]
Also here's a screen capture of some weird characters now appearing on the
pages. I went ahead and disabled the plugin to protect SEO

**Comment by mykkal** [comment]
[image: image.png]
--
Mike McKoy
770-203-8805

**Comment by mykkal** [comment]
Okay so i found the conflict showing weird characters was unrelated. However i'm still getting these errors and the queue shows empty in wordpress while its full in the datbaase.

Warning: foreach() argument must be of type array|object, string given in /home/ironpalm/public_html/wp-content/plugins/video-embed-thumbnail-generator/src/admin/videopack-ffmpeg.php on line 1590

Not sure I can use the plugin or that its ever been functioning.

**Comment by kylegilman** [comment]
Did you try doing the [unserialize](https://www.unserialize.com/) on the full database entry? I don't know for sure what's causing your problem. I have heard that extremely large queues sometimes cause errors because of the way WordPress saves options, and since you weren't able to paste the whole queue I thought that might be it. 

If wp-cron isn't working I would try to get it working. The problem could be related to whatever's stopping Videopack from working. [WP Control](https://wordpress.org/plugins/wp-crontrol/) is a good place to start when troubleshooting wp-cron.

**Comment by mykkal** [comment]
Okay wp cron appears to be fixed. However I still get this error:  Warning: foreach() argument must be of type array|object, string given in /*****/public_html/wp-content/plugins/video-embed-thumbnail-generator/src/admin/videopack-ffmpeg.php on line 1590

**Comment by kylegilman** [comment]
Next step, try deleting the whole kgvid_video_embed_queue database entry in wp_options just to clear out all the junk.

**Comment by mykkal** [comment]
Alrighty so I cleared it out. We'll see if this works. I'll try to encode another video. 
I checked the wp-cron log and didn't see an event mentioning videopack. is there one?

**Comment by mykkal** [comment]
Okay so I tried adding a video to the encoding queue and found no record of it in the database or the wordpress queue. As far as I can see the plugin hasn't worked in my environment since Dec 2022. That's when the last video uploaded was encoded into different formats. 

Not seeing any errors since the db table is cleared. Should I delete the kgvid_video_embed_queue entry altogether?

**Comment by mykkal** [comment]
Hey Kyle? Still on deck? I do need help still. Please.

**Comment by kylegilman** [comment]
You could try deleting the kgvid_video_embed_queue entry. It shouldn't make anything worse.
What PHP version are you running on your server?
Have you tried installing an [older version of the plugin](https://wordpress.org/plugins/video-embed-thumbnail-generator/advanced/) to see if it works? I'd try [v4.7.5](https://downloads.wordpress.org/plugin/video-embed-thumbnail-generator.4.7.5.zip)

**Comment by mykkal** [comment]
Hey Kyle, I did try and was able to encode some videos but I get a lot of errors. Warning: Undefined array key 20 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 20 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 22 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 22 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 23 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 23 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 24 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 24 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 26 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 26 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 27 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 27 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

Warning: Undefined array key 28 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4282

Warning: Undefined array key 28 in /public_html/wp-content/plugins/video-embed-thumbnail-generator/video-embed-thumbnail-generator.php on line 4348

**Comment by mykkal** [comment]
Hi Kyle, I know you're busy. Just wanted to follow up with you.

**Comment by kylegilman** [comment]
Sorry @mykkal, I'm totally stumped.

**Comment by mykkal** [comment]
Problem disappeared. Not sure what caused it.
