### ISSUE TITLE
Multiple resolution via custom shortcode

### ISSUE THREAD

**Issue by zichaprod** [kylegilman/video-embed-thumbnail-generator#522]
Hello,
Is there a way to add multiple resolution in a custom short code they are already encoded in the right format? 
because i host video files in a different place and i can't add it in the WP media library. 

Thanks

**Comment by kylegilman** [comment]
Yes, if you follow the naming structure that Videopack uses. Check out these instructions and let me know if that doesn't work for you https://www.videopack.video/docs/switching-resolutions-without-ffmpeg/
