### ISSUE TITLE
Add option to not insert shortcode

### ISSUE THREAD

**Issue by kylegilman** [kylegilman/video-embed-thumbnail-generator#530]
https://wordpress.org/support/topic/set-wordpress-default-as-default-insert-value-for-video/

**Comment by janvitos** [comment]
Do you prefer adding a user-selectable option, or a filter as I suggested?

I can always create a pull request for the filter if you want.

**Comment by kylegilman** [comment]
I think I'll do both. Happy to take a look at your filter.

**Comment by janvitos** [comment]
Sure.

In videopack-admin.php, lines 341 to 344 :
```
	$options        = kgvid_get_options();
	$kgvid_postmeta = get_post_meta( $post_id, '_kgvid-meta', true );
	$meta_key_array = array(
		'embed'               => 'Single Video',
```
Replace with:
```
	$embed_value 	= apply_filters( 'kgvid_default_embed_value', 'Single Video' );
	$options        = kgvid_get_options();
	$kgvid_postmeta = get_post_meta( $post_id, '_kgvid-meta', true );
	$meta_key_array = array(
		'embed'               => $embed_value,
```

**Comment by kylegilman** [comment]
I see. I think you could use the existing '[kgvid_attachment_meta](https://github.com/kylegilman/video-embed-thumbnail-generator/blob/78501a3ee14a6d492948de704dccfd0b267f3f78/src/admin/videopack-admin.php#L429)' filter for that, right?

**Comment by janvitos** [comment]
Not sure. I will look it up!

**Comment by janvitos** [comment]
You are totally right! Got it working with this code:

add_filter( 'kgvid_attachment_meta', function( $args ) {
    $args['embed'] = 'WordPress Default';
    return $args;
});

No need for this ticket then :) Can be closed.

**Comment by kylegilman** [comment]
Great! I added the option and it'll be in the next release, but I'll leave the filter as-is.
