### ISSUE TITLE
Can not change the thumbnail after it has been set

### ISSUE THREAD

**Issue by roland-strasser** [kylegilman/video-embed-thumbnail-generator#533]
Hello Kyle,

I am trying to change the thumbnail after it has been set. But sadly, the change won't take effect. It just keeps using the old image.

I included a video so you can see the steps to reproduce it:
https://github.com/kylegilman/video-embed-thumbnail-generator/assets/99735020/1daf0225-4533-4106-a0b6-fa888caf7afd

To me, it looks like the custom fields for the plugin recognize the 
change, but the feature image of the post itself doesn't change.

I did create a new empty Website with only Videopack installed, so this should not be caused by other plugins. (WordPress version: 6.4.2)

If you need more information or logs, just let me know. 🙂

**Comment by kylegilman** [comment]
Yeah, I think you've diagnosed it correctly. I've been neglecting testing on selecting thumbnails from the Media Library. I'll try to come up with a fix for that soon.

**Comment by kylegilman** [comment]
To do:

- [ ] In 'upload' Media Library pages, the MediaElement player in the main window disappears after picking a thumbnail.
- [ ] Picking a thumbnail in 'post' Edit pages should not update featured image until the video is inserted.
- [ ] Featured images aren't updated for browser-generated thumbnails in 'post' page.

**Comment by roland-strasser** [comment]
The update fixed it. Thank you.
