### ISSUE TITLE
Meta Box compatibility

### ISSUE THREAD

**Issue by Paulsky** [kylegilman/video-embed-thumbnail-generator#542]
Hello,

Thank you for this great plugin. I'm using Meta Box for custom fields. For a custom post type, I'm using https://docs.metabox.io/fields/file-advanced/ for creating a field where I can select and attach multiple video's. Like this:

```
add_filter( 'rwmb_meta_boxes', 'register_meta_boxes' );

function register_meta_boxes( $meta_boxes ) {
    $meta_boxes[] = [
        'title'   => 'Field Group',
        'id'      => 'untitled',
        'context' => 'normal',
        'fields'  => [
            [
                'type'      => 'file_advanced',
                'name'      => 'Video gallery',
                'id'        => 'video_gallery',
                'mime_type' => 'video/*',
                'multiple'  => true
            ],
        ],
    ];

    return $meta_boxes;
}
```

But, unfortunately, VideoPack breaks this functionality. Is there a way I can disable VideoPack when editing/creating that specific custom post type?

Thank you in advance!

**Comment by kylegilman** [comment]
What specifically is breaking? Does the meta box not appear on the page or is there something in the meta box that doesn't work? Videopack has its hooks in a lot of things, but not meta boxes, so it's hard for me to figure out what you would need to disable just based on that code. Is there a problem with the media library selection window? Do you see any errors in your browser's developer console?

**Comment by Paulsky** [comment]
Thank you for your reply. Please see the screenshots. One with VideoPack enabled, one with VideoPack disabled. I'm digging into the code, and so far I figured out I need to disable the table generation.  There are all kinds of error's because the wrong HTML is loaded inside the wrong elements.

Working:

<img width="290" alt="advanced-field-working" src="https://github.com/kylegilman/video-embed-thumbnail-generator/assets/9481318/495c8a28-ee58-467b-b959-23964c1596c2">

Not working:

<img width="356" alt="advanced-field-not-working" src="https://github.com/kylegilman/video-embed-thumbnail-generator/assets/9481318/be730eed-7207-4b59-a5fe-cbe549a3cc50">

**Comment by kylegilman** [comment]
Maybe attachment_fields_to_edit is incorrectly firing there and adding in all the Videopack attachment fields?

**Comment by Paulsky** [comment]
That could be it. Please see the generated HTML:

<img width="618" alt="advanced-field-html" src="https://github.com/kylegilman/video-embed-thumbnail-generator/assets/9481318/f6756f81-8b69-4315-af83-81541ab46bdd">

**Comment by Paulsky** [comment]
Ah yeah, thank you. I think I 'fixed it' (disabled the functionality) with `remove_filter( 'attachment_fields_to_edit', 'kgvid_image_attachment_fields_to_edit', 10, 2 );`
